version: "3.4"

services:

  edge_proxy:
    image: nginx:1.19.1
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - edge
    ports:
      - 8000:80

  localhost1_1:
    image: routetroubleshootingapi
    hostname: localhost1_INSTANCIA_1
    environment:
      - APP_NAME=localhost1_INSTANCIA_1
    networks:
      - edge
  
  localhost1_2:
    image: routetroubleshootingapi
    hostname: localhost1_INSTANCIA_2
    environment:
      - APP_NAME=localhost1_INSTANCIA_2
    networks:
      - edge

  localhost2:
    image: routetroubleshootingapi
    hostname: localhost2_INSTANCIA_1
    environment:
      - APP_NAME=localhost2_INSTANCIA_1
    networks:
      - edge

networks:
  edge: 
    driver: bridge